name: Publish MessageBus NuGet

on:
  push:
    branches: [ master ] # Dispara quando você sobe código para a master

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: dotnet build GeekShopping.MessageBus.csproj --configuration Release

      - name: Test
        run: dotnet test GeekShopping.MessageBus.Test/GeekShopping.MessageBus.Test.csproj --configuration Release --no-build --nologo -v m

      - name: Pack
        run: dotnet pack -c Release -o out
        
      - name: Push to GitHub Packages
        run: dotnet nuget push out/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}